[package]
name = "falk"
version = "0.1.0"
authors = ["Mathias <mathias@c8c4.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
